### PR TITLE
Make title better

### PR DESCRIPTION
**Pull request by pjbull**

### CODE REVIEW

**Review by isms — CHANGES_REQUESTED** [review]
How about "MCMC Diagnostics in Rust"?

**Comment by pjbull** [comment]
Doesn't our styleguide say that headings should be sentence case, not title case?

**Comment by isms** [comment]
Great point, please update accordingly 👍🏻

**Comment by pjbull** [comment]
Ready, can you merge ASAP? I need this fix in my project

**Comment by isms** [comment]
Fixed typo. Thanks! Hope you get a free t-shirt :shirt:

**Pull request merged**
